name: Code Coverage

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.x

    - name: Restore Dependencies
      run: dotnet restore

    - name: Run Tests and Collect Code Coverage
      run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

    - name: Upload Code Coverage Report
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage
        path: ./TestResults

    - name: Generate Code Coverage Badge
      run: |
        echo "[![codecov](https://codecov.io/github/asgerbabayev/UnitTest_Example/graph/badge.svg?token=VN8ZLQFPV1)](https://codecov.io/github/asgerbabayev/UnitTest_Example)" > ./README.md
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    - name: Commit and Push Changes
      run: |
        git add README.md
        git commit -m "Update README.md with code coverage badge"
        git push
