name: Code Coverage

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.x

    - name: Restore Dependencies
      run: dotnet restore

    - name: Run Tests and Collect Code Coverage
      run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

    - name: Upload Code Coverage Report
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage
        path: ./TestResults

    - name: Generate Code Coverage Badge
      run: |
        bash <(curl -s https://codecov.io/bash) -f ./TestResults/coverage.opencover.xml -t ${{ secrets.CODECOV_TOKEN }}

